### ISSUE TITLE
Perform additional accessibility checks

### ISSUE THREAD

**Issue by deSagaz** [co-teach/website#3]
Using [axe](https://chrome.google.com/webstore/detail/axe-web-accessibility-tes/lhdoppojpmngadmnindnejefpokejbdd) and the [W3C tool](https://validator.w3.org/nu/).

**Comment by lfb0801** [comment]
Maybe [lighthouse-ci](https://github.com/GoogleChrome/lighthouse-ci) is a better suited testing tool.

**Comment by deSagaz** [comment]
> 
> 
> Maybe [lighthouse-ci](https://github.com/GoogleChrome/lighthouse-ci) is a better suited testing tool.

Thanks for the suggestion, @lfb0801! The CI suite is now running on this repo.
